[cloud_server]
server1 ansible_host=3.89.242.204 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/inception-key.pem
server2 ansible_host=54.235.232.17 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/cloudTest-1.pem
