- name: Create DigitalOcean Droplet
  hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - droplet

  
- name: Deploy Inception to Cloud Servers
  hosts: cloud_server

  roles:
    - setup
    - common
    - mariadb
    - wordpress
    - nginx 
    - systemd
  
  post_tasks:
    - name: Display deployment info
      debug:
        msg: "WordPress deployed to https://{{ ansible_host }}"

